### ISSUE TITLE
Update all existing mentions of the security@edx.org mailing list in the `openedx` github org to mention security@openedx.org instead.

### ISSUE THREAD

**Issue by feanil** [openedx/wg-security#16]

**Comment by pshiu** [comment]
From Security WG meeting: There may be PR's out there for this already! Remaining work is to verify any deltas that remain.

**Comment by feanil** [comment]
Still true, do the verifying!

**Comment by robrap** [comment]
@feanil: Could the PR description point to the relevant process doc for how the new email will be used? Thank you.

**Comment by feanil** [comment]
@robrap I'm not sure exactly what you mean, it should be used to report security issues the same as the old one,  is there something specific you're looking for?

**Comment by robrap** [comment]
@feanil: I was curious how the email works now vs how it worked before, and didn’t know if there was a doc that explained.

**Comment by feanil** [comment]
If you're asking about how it's processed, it's now processed by the Open edX security working group and triaged to operators if it makes sense to do so.

**Comment by feanil** [comment]
All repos have been updated with the correct e-mail address.
