### ISSUE TITLE
Write up on-boarding and off-boarding steps for a new security WG Member

### ISSUE THREAD

**Issue by feanil** [openedx/wg-security#17]

**Comment by pshiu** [comment]
Started at: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3630858436/For+working+group+members#Onboarding-%26-Offboarding

**Comment by pshiu** [comment]
Blocked: waiting for any additional accesses & updates for:
* post tCRIL private repo moves
* security manager role in openedx

**Comment by feanil** [comment]
@pshiu looks good, does it make sense to just mark this as done and create a new ticket for adding those last two permissions?
