### ISSUE TITLE
Update Security Policy and SECURITY.md

### ISSUE THREAD

**Issue by feanil** [openedx/wg-security#2]
Currently [SECURITY.md](https://github.com/openedx/.github/blob/master/SECURITY.md) points to the edX security policy. We need to publish the Open edX security Policy and then update the document to point to this instead.

Should the new security policy just live in SECURITY.md? Should it live somewhere else?

We should also include the security contact info in SECURITY.md so people know how to report issues.

**Comment by alangsto** [comment]
Draft of new policy here: https://docs.google.com/document/d/1zqbKgVN1EJZBVsv2F6wOMjGX1an1wssq05W1Yli1qSA/edit#

**Comment by alangsto** [comment]
@feanil updated based on suggestions

**Comment by feanil** [comment]
Sounds good,  I'll send it off to Nell for review but she's on vacation for the next 10 days so it will be a while before we hear back.

**Comment by alangsto** [comment]
@alangsto will email Nell to ask if the security policy should live anywhere else besides security.md
