### ISSUE TITLE
Update onboarding doc with any changes post-tCRIL private repo moves

### ISSUE THREAD

**Issue by pshiu** [openedx/wg-security#20]
Update our [onboarding/offboarding doc](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3630858436/For+working+group+members#Onboarding-%26-Offboarding) with any additional accesses & updates for:

* post tCRIL private repo moves
* security manager role in openedx

Blocked until tCRIL private repo moves are complete.

**Comment by pshiu** [comment]
Continuation of #17.

**Comment by feanil** [comment]
Moved the on/off-boarding docs to [the playbooks page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3769139248/Security+Playbooks+for+Security+WG+members), they were duplicated to the page linked above so removed them.

The docs have been updated post tCRIL private repo move.
