### ISSUE TITLE
Add Security Policy to docs.openedx.org

### ISSUE THREAD

**Issue by pshiu** [openedx/wg-security#32]
Follow-on work to https://github.com/openedx/wg-security/issues/2.

Link to Security Policy in docs.openedx.org.

See email from Feanil to Nell/Ali/Phil on May 10, 2023, 12:39 PM EDT with subject "Open edX Security Policy".

**Comment by alangsto** [comment]
PR: https://github.com/openedx/docs.openedx.org/pull/388
